/**
 * ts01-happy-path.spec.ts
 *
 * QAForge DEMO-001 — Event Detail CTA Button — Status-Driven Behavior
 *
 * Generated by: QAForge Playwright Automation Engineer
 * Story ticket: DEMO-001
 * Artifact: 05_execution_evidence/
 *
 * Covers:
 *   AC-01 — On-sale event shows "Buy Tickets" CTA (inline + sticky)
 *   AC-02 — Pre-sale event shows "Get Notified" CTA and opens modal
 *   AC-03 — CMS-disabled event shows no CTA button
 *   AC-04 — Sticky CTA appears after scrolling past hero section
 */

import { test, expect } from '../../fixtures/eventFixtures';

test.describe('DEMO-001 — Event Detail CTA — On-Sale Event', () => {

  test('TC-01-01 — On-sale event renders "Buy Tickets" inline CTA', async ({ eventPage, onSaleEvent }) => {
    await eventPage.goto(onSaleEvent.id);

    await expect(eventPage.ctaButton).toBeVisible();
    await expect(eventPage.ctaButton).toHaveText('Buy Tickets');
  });

  test('TC-01-02 — On-sale sticky CTA appears after scrolling past hero', async ({ eventPage, onSaleEvent }) => {
    await eventPage.goto(onSaleEvent.id);

    // Sticky CTA should NOT be visible before scrolling
    await expect(eventPage.stickyCtaButton).not.toBeVisible();

    await eventPage.scrollPastHero();

    // Sticky CTA should be visible and show same label
    await expect(eventPage.stickyCtaButton).toBeVisible();
    await expect(eventPage.stickyCtaButton).toHaveText('Buy Tickets');
  });

  test('TC-01-03 — Sticky CTA disappears when user scrolls back to top', async ({ eventPage, onSaleEvent }) => {
    await eventPage.goto(onSaleEvent.id);

    await eventPage.scrollPastHero();
    await expect(eventPage.stickyCtaButton).toBeVisible();

    await eventPage.scrollToTop();
    await expect(eventPage.stickyCtaButton).not.toBeVisible();
  });

});

test.describe('DEMO-001 — Event Detail CTA — Pre-Sale Event', () => {

  test('TC-02-01 — Pre-sale event renders "Get Notified" inline CTA', async ({ eventPage, presaleEvent }) => {
    await eventPage.goto(presaleEvent.id);

    await expect(eventPage.ctaButton).toBeVisible();
    await expect(eventPage.ctaButton).toHaveText('Get Notified');
  });

  test('TC-02-02 — Clicking "Get Notified" opens the pre-sale registration modal', async ({ eventPage, presaleEvent }) => {
    await eventPage.goto(presaleEvent.id);

    await eventPage.clickCtaButton();

    await expect(eventPage.presaleModal).toBeVisible();
  });

  test('TC-02-03 — Pre-sale sticky CTA appears after scrolling past hero', async ({ eventPage, presaleEvent }) => {
    await eventPage.goto(presaleEvent.id);

    await eventPage.scrollPastHero();

    await expect(eventPage.stickyCtaButton).toBeVisible();
    await expect(eventPage.stickyCtaButton).toHaveText('Get Notified');
  });

});

test.describe('DEMO-001 — Event Detail CTA — CMS-Disabled Event', () => {

  test('TC-03-01 — Disabled event does not render inline CTA button', async ({ eventPage, disabledEvent }) => {
    await eventPage.goto(disabledEvent.id);

    await expect(eventPage.ctaButton).not.toBeVisible();
  });

  test('TC-03-02 — Disabled event does not render sticky CTA after scrolling', async ({ eventPage, disabledEvent }) => {
    await eventPage.goto(disabledEvent.id);

    await eventPage.scrollPastHero();

    await expect(eventPage.stickyCtaButton).not.toBeVisible();
  });

});

test.describe('DEMO-001 — API contract — Event status field', () => {

  test('TC-04-01 — On-sale event API returns status: on_sale', async ({ apiClient, onSaleEvent }) => {
    const { status, body } = await apiClient.getEvent(onSaleEvent.id);

    expect(status).toBe(200);
    expect(body.status).toBe('on_sale');
    expect(body.cta_disabled).toBe(false);
  });

  test('TC-04-02 — Pre-sale event API returns status: presale', async ({ apiClient, presaleEvent }) => {
    const { status, body } = await apiClient.getEvent(presaleEvent.id);

    expect(status).toBe(200);
    expect(body.status).toBe('presale');
    expect(body.cta_disabled).toBe(false);
  });

  test('TC-04-03 — Disabled event API returns cta_disabled: true', async ({ apiClient, disabledEvent }) => {
    const { status, body } = await apiClient.getEvent(disabledEvent.id);

    expect(status).toBe(200);
    expect(body.cta_disabled).toBe(true);
  });

  test('TC-04-04 — Non-existent event returns 404', async ({ apiClient }) => {
    const { status } = await apiClient.getEvent('evt_does_not_exist');

    expect(status).toBe(404);
  });

});
